#Only apply this file if you are testing the production schema in a local environment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-deployment
  namespace: magento-demo-production
  annotations:
    "cluster-autoscaler.kubernetes.io/safe-to-evict": "false"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
      annotations:
        "cluster-autoscaler.kubernetes.io/safe-to-evict": "true"
    spec:
      containers:
        - name: database
          image: mariadb:10.4.26
          env:
          - name: MYSQL_ROOT_PASSWORD
            value: "${MYSQL_ROOT_PASSWORD}" # Replace with environment variable
          - name: MYSQL_DATABASE
            value: "magento"
          - name: TZ
            value: "UTC"
          - name: MYSQL_USER
            value: "magento"
          - name: MYSQL_PASSWORD
            value: "${MYSQL_PASSWORD}" # Replace with environment variable
          resources:
            limits:
              memory: '2000Mi'
              cpu: '300m'
            requests:
              memory: '2000Mi'
              cpu: '300m'
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: 'kubernetes.io/arch'
                    operator: In
                    values:
                      - arm64

---

apiVersion: v1
kind: Service
metadata:
  name: database-service
  namespace: magento-demo-production
  labels:
    app: database
spec:
  selector:
    app: database
  ports:
    - protocol: 'TCP'
      port: 3306
      targetPort: 3306
  type: ClusterIP
