#Redis (Sessions)
#Only apply this file if you are testing the production schema in a local environment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-session-deployment
  namespace: magento-demo-production
  annotations:
    "cluster-autoscaler.kubernetes.io/safe-to-evict": "false"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-session
  template:
    metadata:
      labels:
        app: redis-session
      annotations:
        "cluster-autoscaler.kubernetes.io/safe-to-evict": "true"
    spec:
      containers:
        - name: redis-session
          image: redis:6-alpine
          resources:
            limits:
              memory: '1200Mi'
              cpu: '300m'
            requests:
              memory: '1200Mi'
              cpu: '300m'
      tolerations:
        - key: "kubernetes.io/arch"
          operator: "Equal"
          value: "arm64"
          effect: "NoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: 'kubernetes.io/arch'
                    operator: In
                    values:
                      - arm64

---

apiVersion: v1
kind: Service
metadata:
  name: redis-session-service
  namespace: magento-demo-production
  labels:
    app: redis-session
spec:
  selector:
    app: redis-session
  ports:
    - protocol: 'TCP'
      port: 6380
      targetPort: 6379
  type: ClusterIP
