apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-var-export
  namespace: magento-demo-production
spec:
  volumeName: pv-var-export
  storageClassName: efs-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
