apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-var-import
  namespace: magento-demo-production
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  accessModes:
    - ReadWriteMany
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-e8a95a42
