apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-pub-media
  namespace: magento-demo-production
spec:
  volumeName: pv-pub-media
  storageClassName: efs-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
