apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-var-report
  namespace: magento-demo-production
spec:
  volumeName: pv-var-report
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
