apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: magento-front-phpfpm-hpa
  namespace: magento-demo-production
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: magento-front-nginx-deployment
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 85
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 85
status:
  desiredReplicas: 1
  conditions:
    - type: 'ScalingLimited'
      status: 'True'
  currentReplicas: 1
