name: Build Nginx Images

on:
  push:
    branches:
      - 'master'
    paths:
      - 'nginx/**'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug

jobs:
  nginx:
    name: Nginx base
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Create image
        uses: elgohr/Publish-Docker-Github-Action@v4
        with:
          name: imagination-media/magento-k8s/nginx
          username: igor-imaginemage
          password: ${{ secrets.NODE_AUTH_TOKEN }}
          registry: ghcr.io
          tags: latest
          workdir: nginx/base
          platforms: linux/amd64,linux/arm64

  nginx_gcsfuse:
    name: Nginx base + Gcsfuse
    runs-on: ubuntu-latest
    needs: [ nginx ]
    steps:
      - uses: actions/checkout@master

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Create image
        uses: elgohr/Publish-Docker-Github-Action@v4
        with:
          name: imagination-media/magento-k8s/nginx
          username: igor-imaginemage
          password: ${{ secrets.NODE_AUTH_TOKEN }}
          registry: ghcr.io
          tags: latest-gcsfuse
          workdir: nginx/gcsfuse
          platforms: linux/amd64,linux/arm64
