name: Build PHP-FPM 8.1 Image

on:
  push:
    branches:
      - 'master'
#    paths:
#      - 'php-fpm/8.1/**'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug

jobs:
  image:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Create image
        uses: elgohr/Publish-Docker-Github-Action@v4
        with:
          name: imagination-media/magento-k8s/php-fpm
          username: igor-imaginemage
          password: ${{ secrets.NODE_AUTH_TOKEN }}
          registry: ghcr.io
          tags: 8.1
          workdir: php-fpm/8.1
          platforms: linux/amd64,linux/arm64
