name: Build PHP-FPM 8.1 Image

on:
  push:
    branches:
      - 'master'
    paths:
      - 'php-fpm/8.1/**'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug

jobs:
  x64_image:
    name: x64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Create image
          uses: elgohr/Publish-Docker-Github-Action@v4
          with:
            name: imagination-media/magento-k8s/php-fpm
            username: igor-imaginemage
            password: ${{ secrets.NODE_AUTH_TOKEN }}
            registry: ghcr.io
            tags: 8.1
            workdir: php-fpm/8.1

  arm64_image:
    name: arm64
    runs-on: [self-hosted, linux, ARM64]
    steps:
      - uses: actions/checkout@master

      - name: Create image
          uses: elgohr/Publish-Docker-Github-Action@v4
          with:
            name: imagination-media/magento-k8s/php-fpm
            username: igor-imaginemage
            password: ${{ secrets.NODE_AUTH_TOKEN }}
            registry: ghcr.io
            tags: 8.1
            workdir: php-fpm/8.1
