name: Build PHP-FPM 7.3 Images

on:
  push:
    branches:
      - 'master'
    paths:
      - 'php-fpm/7.3/**'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug

jobs:
  php_fpm_73:
    name: Php-fpm (7.3)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Create image
        uses: elgohr/Publish-Docker-Github-Action@v4
        with:
          name: imagination-media/magento-k8s/php-fpm
          username: igor-imaginemage
          password: ${{ secrets.NODE_AUTH_TOKEN }}
          registry: ghcr.io
          tags: 7.3
          workdir: php-fpm/7.3/base
          platforms: linux/amd64,linux/arm64

  php_fpm_73_gcsfuse:
    name: Php-fpm (7.3) + Gcsfuse
    runs-on: ubuntu-latest
    needs: [ php_fpm_73 ]
    steps:
      - uses: actions/checkout@master

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Create image
        uses: elgohr/Publish-Docker-Github-Action@v4
        with:
          name: imagination-media/magento-k8s/php-fpm
          username: igor-imaginemage
          password: ${{ secrets.NODE_AUTH_TOKEN }}
          registry: ghcr.io
          tags: 7.3-gcsfuse
          workdir: php-fpm/7.3/gcsfuse
          platforms: linux/amd64,linux/arm64
